clear;

% Open SQLite DB connection. This code assumes that the database is
% freshly created and empty (sqlite3 shimmer.db < shimmer.sql)
dbfile = fullfile(pwd, "../../sqlite/shimmer.db");
conn = sqlite(dbfile);

station_types_tab = sqlread(conn, "station_types");

%station_types_tab{station_types_tab.t_type == 1, ["t_limits_table", "t_profile_table"] }

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Define stations. I am doing this using cells, but it can also be done
% using table() and specifiying column-oriented data.
% Here we are inserting s_number, s_name and t_type columns.
stations = { ...
     1, "s01_entry", 0; ...
     2, "s02_exit",  2; ...
     3, "s03_junct", 3; ...
     4, "s04_junct", 3; ...
     5, "s05_junct", 3; ...
     6, "s06_exit",  4; ...
     7, "s07_junct", 3; ...
     8, "s08_junct", 3; ...
     9, "s09_exit",  4; ...
    10, "s10_junct", 3; ...
    11, "s11_exit",  4; ...
    12, "s12_entry", 1; ...
    13, "s13_exit",  2 };

% Convert cell to a table
stations_tab = cell2table(stations, ...
    "VariableNames", ["s_number", "s_name", "t_type"] );

% Write the table to the SQL DB
sqlwrite(conn, "stations", stations_tab);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Define pipelines.
% Here we are inserting p_name, s_from, s_to and p_type columns.

pipelines = { ...
    "pipe01",  1,  4, 0; ...
    "pipe02",  2,  3, 0; ...
    "pipe03",  3,  4, 0; ...
    "pipe05",  4,  5, 0; ...
    "pipe04",  3,  5, 0; ...
    "pipe06",  5,  6, 0; ...
    "pipe07",  5, 14, 0; ...
    "pipe09",  8,  7, 0; ...
    "pipe08",  7,  5, 0; ...
    "pipe10", 12,  7, 0; ...
    "pipe11", 13,  8, 0; ...
    "pipe12",  9,  8, 0; ...
    "pipe13",  8, 10, 0; ...
    "pipe14", 10, 11, 0; ...
    "pipe15",  4, 10, 0; ...
    "pipe16", 14, 15, 2; ...
    "pipe17", 15, 18, 0 };

% Convert cell to a table
pipelines_tab = cell2table(pipelines, ...
    "VariableNames", ["p_name", "s_from", "s_to", "p_type"] );

% Write the table to the SQL DB
sqlwrite(conn, "pipelines", pipelines_tab);

close(conn);

